version: '3.1'

services: 

  localstack:
    image: localstack/localstack:1.1
    hostname: localstack
    environment: 
      - AWS_DEFAULT_REGION=eu-west-2
      - EDGE_PORT=4566
      - SERVICES=s3,ses
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=foo
      - DEBUG=1
      - HOSTNAME_EXTERNAL=localstack
    ports: 
      - '4566-4583:4566-4583'
    volumes: 
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"